// Semantic acceptance cases promoted from the October audit. Synthetic data only.
const fs=require('node:fs'),assert=require('node:assert/strict');
const root=require('node:path').resolve(__dirname,'../..');
const {JSDOM}=require(root+'/tests/prose/node_modules/jsdom');
const outdir=process.env.NICU_AUDIT_OUTPUT||'';
const html=fs.readFileSync(root+'/index.html','utf8').replace('function render(){','window.auditAPI={S,render,supportSentence,sourceStamp,resolvedSupport,readmitEpisodes,readmitModuleNarrative};function render(){');
const results=[];
const saveResult=r=>{const i=results.findIndex(x=>x.id===r.id);if(i<0)results.push(r);else results[i]=r;};
function page(){
 const errors=[],dom=new JSDOM(html,{runScripts:'dangerously',pretendToBeVisual:true,url:'https://nicu-synthetic-audit.test/',beforeParse(W){
  const D=W.Date,fixed=new D(2026,9,4,12).getTime();W.Date=class extends D{constructor(...args){super(...(args.length?args:[fixed]));}static now(){return fixed;}};
  W.scrollTo=()=>{};W.HTMLElement.prototype.scrollIntoView=()=>{};W.addEventListener('error',e=>errors.push(String(e.error?.stack||e.message)));
 }});
 const W=dom.window,d=W.document,steps=[];
 const get=s=>{const e=d.querySelector(s);assert.ok(e,'Missing '+s);return e;};
 const click=s=>{const e=get(s);assert.equal(e.disabled,false,'Disabled '+s);steps.push({click:s,label:e.textContent.trim()});e.click();};
 const input=(id,v)=>{const e=get('#'+id);assert.equal(e.readOnly||e.disabled,false,'Not editable '+id);e.value=v;steps.push({input:id,value:v});e.dispatchEvent(new W.Event(e.tagName==='SELECT'?'change':'input',{bubbles:true}));};
 const seg=(k,v)=>click(`[data-seg="${k}"] [data-v="${v}"]`),msel=(k,v)=>click(k.startsWith('rm_')?`[data-rm-chip="${k}"][data-v="${v}"]`:`[data-msel="${k}"] [data-v="${v}"]`),phase=p=>click(`[data-phase-target="${p}"]`),choice=(f,v)=>click(`#${f}-choice-${v}`);
 const api={W,d,get,click,input,seg,msel,phase,choice,steps,errors,close:()=>W.close(),note:()=>get('#note').textContent.trim()};
 api.base=(story='D')=>{
  click(`[data-story="${story}"]`);seg('dest',story==='E'?'NBC':'NICU');
  input('birthDate',story==='E'?'2026-09-20':'2026-10-04');input('birthTime','10:00');
  seg('gender','male');input('gaW','39');input('gaD','0');input('bw','3200');seg('delivery','nsd');
  input('matAge','31');input('gravida','2');input('para','1');input('ap1','8');input('ap5','9');input('ancPlace','TPEMMH');
  if(story==='D')input('obFacility','Example Birth Hospital');
  if(story==='E'){input('birthHosp','Example Birth Hospital');seg('readmitSource','clinic');}
 };
 api.supportSource=(mode)=>{input('birthFinalSupport',mode);phase('course:obCare');if(mode)choice('obM1Relation','continued');phase('course:route');};
 api.event=(stage,kind)=>{phase(stage==='birth'?'birth:dr':'course:'+({outside:'obCare',arrival:'obArrive',transport:'route'}[stage]));
  if(stage==='birth'){input('birthResusStatus','performed');click(`[data-add-birth="${kind}"]`);}else click(stage==='transport'?`[data-add-course="${kind}"]`:`[data-event-phase="${stage}"][data-add-stage-event="${kind}"]`);
  return W.auditAPI.S[stage==='birth'?'birthEvents':'courseEvents'].at(-1).id;};
 api.capture=()=>{
  click('[data-tab="adm"]');const review={conflicts:get('#reviewConflictList').textContent.trim(),pending:get('#reviewPendingList').textContent.trim(),missing:get('#reviewMissingList').textContent.trim()};
  const notes={};for(const t of ['adm','acc','plan','proc']){click(`[data-tab="${t}"]`);notes[t]=api.note();}
  return {notes,review,procedureIntubation:get('[data-proctog] [data-v="intub"]').getAttribute('aria-pressed'),errors};
 };
 return api;
}
function test(id,description,setup,expect){
 if(process.env.AUDIT_FILTER&&!new RegExp(process.env.AUDIT_FILTER).test(id))return;
 const p=page();try{setup(p);const captured=p.capture();let status='pass',reason='';try{assert.deepEqual(p.errors,[]);expect?.(captured,p);}catch(e){status='fail';reason=e.message;}
  const r={id,description,status,reason,steps:p.steps,...captured};saveResult(r);console.log(JSON.stringify({id,status,reason:reason.split('\n')[0]}));
 }catch(e){saveResult({id,description,status:'harness-error',reason:e.stack,steps:p.steps});console.log(JSON.stringify({id,status:'harness-error',reason:e.message}));}finally{p.close();}
 if(outdir)fs.writeFileSync(outdir+'/semantic-results.json',JSON.stringify(results,null,2));
}
const both=(r,check)=>{for(const t of ['adm','acc'])check(r.notes[t],t);};
test('G01','One selected plural symptom must use were',p=>{p.base('D');p.phase('course:route');p.msel('obSx','subcostal retractions');},r=>both(r,n=>assert.match(n,/subcostal retractions were noted/)));
test('G02','Negative pale stools must use were',p=>{p.base('E');p.msel('readmitProblems','jaundice');p.msel('readmitJaundiceSigns','no pale stools');},r=>both(r,n=>assert.match(n,/No pale stools were reported/)));
test('G03','Positive pale stools must use were',p=>{p.base('E');p.msel('readmitProblems','jaundice');p.msel('readmitJaundiceSigns','pale stools');},r=>both(r,n=>assert.match(n,/Pale stools were reported/)));
test('G04','Neither/nor agrees with nearest plural noun',p=>{p.base('E');p.msel('readmitProblems','jaundice');p.msel('readmitJaundiceSigns','no dark urine');p.msel('readmitJaundiceSigns','no pale stools');},r=>both(r,n=>assert.match(n,/Neither dark urine nor pale stools were reported/)));
test('S01','Same CPAP with changed settings must not claim a new mode',p=>{p.base();p.supportSource('cpap');p.choice('obRespRelation','settings');p.input('obFiO2','40');p.input('obPEEP','6');},r=>both(r,n=>{assert.match(n,/Settings for CPAP were adjusted during transport.*40%.*6 cmH2O/);assert.doesNotMatch(n,/support was changed to CPAP/);}));
test('S02','Restarting ETT support requires explicit reintubation confirmation',p=>{p.base();p.supportSource('ett');p.choice('obRespRelation','repeat');p.seg('obRespType','ett');},r=>{both(r,n=>assert.doesNotMatch(n,/reintubated/));assert.equal(r.procedureIntubation,'false');});
test('S03','Starting support plus room air must be prevented or flagged',p=>{p.base();p.phase('course:obCare');p.choice('obM1Relation','new');assert.equal(p.get('[data-seg="obM1Type"] [data-v="room"]').disabled,true);p.W.auditAPI.S.obM1Type='room';p.W.auditAPI.render();},r=>assert.doesNotMatch(r.review.conflicts,/未發現衝突/));
test('S04','Restarting support plus room air must be prevented or flagged',p=>{p.base();p.phase('course:route');p.choice('obRespRelation','repeat');assert.equal(p.get('[data-seg="obRespType"] [data-v="room"]').disabled,true);p.W.auditAPI.S.obRespType='room';p.W.auditAPI.render();},r=>assert.doesNotMatch(r.review.conflicts,/未發現衝突/));
test('S05','Simple observation never asserts initiation or continuation',p=>{p.base();p.phase('course:obCare');p.seg('obM1Type','o2');},r=>both(r,n=>{assert.match(n,/was receiving supplemental oxygen at the referring hospital/);assert.doesNotMatch(n,/oxygen was (initiated|continued)/);}));
test('S06','Different support mode change is preserved',p=>{p.base();p.supportSource('cpap');p.choice('obRespRelation','changed');p.seg('obRespType','o2');},r=>both(r,n=>assert.match(n,/changed to supplemental oxygen during transport/)));
test('S07','Stopping support does not imply room air or improvement',p=>{p.base();p.supportSource('cpap');p.choice('obRespRelation','stopped');},r=>both(r,n=>{assert.match(n,/CPAP was discontinued during transport/);assert.doesNotMatch(n,/room air|improved/);}));
test('S08','Changed predecessor invalidates continuation',p=>{p.base();p.supportSource('cpap');p.choice('obRespRelation','continued');p.phase('course:obCare');p.choice('obM1Relation','clear');p.seg('obM1Type','ett');},r=>{both(r,n=>assert.doesNotMatch(n,/was continued during transport/));assert.match(r.review.conflicts,/重新確認/);});
test('S09','Clearing outside observation removes its sentence and parameters',p=>{p.base();p.phase('course:obCare');p.seg('obM1Type','o2');p.input('obM1Flow','3');p.choice('obM1Relation','clear');},r=>both(r,n=>assert.doesNotMatch(n,/supplemental oxygen|flow 3 L/)));
test('T01','Distinct outside, arrival and transport events appear once in stage order',p=>{p.base();for(const [stage,note]of [['outside','Synthetic outside event.'],['arrival','Synthetic arrival event.'],['transport','Synthetic transport event.']]){const id=p.event(stage,'cpap');p.input('event-'+id+'-note',note);}},r=>both(r,n=>{for(const w of ['outside','arrival','transport'])assert.equal(n.split('Synthetic '+w+' event.').length,2);assert.ok(n.indexOf('Synthetic outside')<n.indexOf('Synthetic arrival'));assert.ok(n.indexOf('Synthetic arrival')<n.indexOf('Synthetic transport'));}));
test('T02','Outside intubation is not our procedure',p=>{p.base();p.event('outside','intubation');},r=>assert.equal(r.procedureIntubation,'false'));
test('T03','Our explicit on-site intubation is our procedure',p=>{p.base();p.event('arrival','intubation');},r=>assert.equal(r.procedureIntubation,'true'));
test('T04','Supplemental arrival complete sentence keeps subject and tense',p=>{p.base();p.input('obArrival','The infant was tachypneic with mild subcostal retractions.');},r=>both(r,n=>assert.match(n,/On our team's arrival at the referring hospital, the infant was tachypneic with mild subcostal retractions\./)));
test('T05','Late consultation versus early birth event is flagged',p=>{p.base('B');p.input('pwConsultH','1');const id=p.event('birth','ppv');p.input('event-'+id+'-minutes','2');},r=>assert.match(r.review.conflicts,/會診時間晚於/));
test('E01','Complete respiratory readmission: no unrelated bilirubin fields or transport',p=>{p.base('E');p.seg('readmitPrior','uneventful');p.input('readmitDischargeDate','2026-09-23');p.input('readmitDischargeWeight','3050');p.seg('readmitFeeding','breast milk');p.msel('readmitBaseline','feeding well');p.msel('readmitBaseline','active');p.msel('readmitProblems','respiratory');p.input('readmitOnsetDOL','12');p.input('readmitCourseType','new');p.msel('rm_respiratory_symptoms','cough');p.msel('rm_respiratory_symptoms','rhinorrhea');p.input('rm_respiratory_setting','at rest');p.input('readmitUrine','remained adequate');p.input('readmitActivity','remained normal');p.input('readmitSickContact','An older sibling had a cough.');p.input('readmitCurrentWeight','3450');p.input('readmitSpO2','96');p.input('readmitEvaluation','Mild subcostal retractions were noted.');p.input('readmitTreatment','Nasal suction was performed.');p.seg('resp','room air');},r=>both(r,n=>{assert.doesNotMatch(n,/bilirubin|transport team/);assert.match(n,/cough and rhinorrhea/);assert.match(n,/day of life 12/);}));
test('E02','Jaundice readmission retains dates, stool findings and results',p=>{p.base('E');p.seg('readmitPrior','treated');p.input('readmitPriorUnit','NBC');p.input('readmitPriorCourse','received phototherapy for neonatal jaundice');p.input('readmitDischargeDate','2026-09-23');p.msel('readmitProblems','prolonged-jaundice');p.input('rm_jaundice_onset','2');p.input('rm_jaundice_trend','persisted');p.msel('readmitJaundiceSigns','no dark urine');p.msel('readmitJaundiceSigns','no pale stools');p.input('readmitTSB','14.3');p.input('readmitDB','0.4');},r=>both(r,n=>{assert.match(n,/14\.3 mg\/dL/);assert.ok(n.indexOf('day of life 2')<n.indexOf('received phototherapy'));assert.ok(n.indexOf('received phototherapy')<n.indexOf('discharged home'));}));
test('E03','Fever module preserves temperature method and timestamp',p=>{p.base('E');p.msel('readmitProblems','fever');p.input('readmitOnsetDOL','15');p.input('rm_fever_temperature','38.2');p.input('rm_fever_method','rectal');p.input('rm_fever_time','2026-10-04T08:00');},r=>both(r,n=>assert.match(n,/38\.2 °C.*rectal.*2026-10-04 08:00/)));
test('E04','Feeding module zero intake is retained, not mistaken for missing',p=>{p.base('E');p.msel('readmitProblems','poor-feeding');p.input('rm_feeding_usual','60');p.input('rm_feeding_current','0');p.input('rm_feeding_frequency','every 3 hours');},r=>both(r,n=>assert.match(n,/decreased from 60 to 0 mL per feed/)));
test('E05','Single apnea event agreement and explicit recovery',p=>{p.base('E');p.msel('readmitProblems','apnea');p.msel('rm_apnea_type','apnea');p.msel('rm_apnea_type','cyanosis');p.input('rm_apnea_count','1');p.input('rm_apnea_duration','15');p.input('rm_apnea_setting','during feeding');p.input('rm_apnea_recovery','after tactile stimulation');},r=>both(r,n=>{assert.match(n,/1 episode of apnea and cyanosis was reported/);assert.match(n,/15 seconds/);assert.match(n,/recovered after tactile stimulation/);}));
test('E06','Vomiting single episode agrees with singular and preserves characteristic',p=>{p.base('E');p.msel('readmitProblems','gastrointestinal');p.msel('rm_gastrointestinal_symptoms','vomiting');p.input('rm_gastrointestinal_character','nonbilious');p.input('rm_gastrointestinal_count','1');},r=>both(r,n=>assert.match(n,/1 episode of vomiting was reported/)));
test('E07','Screen abnormality is referral, not an invented diagnosis',p=>{p.base('E');p.msel('readmitProblems','abnormal-screen');p.input('rm_screen_test','newborn screening');p.input('rm_screen_result','an elevated screening marker');p.input('rm_screen_date','2026-09-23');},r=>both(r,n=>{assert.match(n,/referred for evaluation/);assert.doesNotMatch(n,/developed.*screening/);}));
test('E08','Care module uses care narrative, not illness onset',p=>{p.base('E');p.seg('readmitSource','scheduled');p.msel('readmitProblems','care');p.input('rm_care_reason','temporary caregiver unavailability');p.input('rm_care_needs','Feeding assistance was requested.');},r=>both(r,n=>{assert.match(n,/temporary caregiver unavailability/);assert.doesNotMatch(n,/developed.*care/);}));
test('E09','Multiple modules at same onset do not repeat the same onset phrase',p=>{p.base('E');for(const x of ['respiratory','fever','poor-feeding'])p.msel('readmitProblems',x);p.input('readmitOnsetDOL','12');p.input('readmitCourseType','new');p.msel('rm_respiratory_symptoms','cough');p.input('rm_fever_temperature','38.1');p.input('rm_feeding_usual','60');p.input('rm_feeding_current','30');},r=>both(r,n=>assert.equal((n.match(/On day of life 12/g)||[]).length,1)));
test('E10','Respiratory-only route hides retained jaundice data',p=>{p.base('E');p.msel('readmitProblems','jaundice');p.input('readmitTSB','15.7');p.msel('readmitProblems','jaundice');p.msel('readmitProblems','respiratory');},r=>both(r,n=>assert.doesNotMatch(n,/15\.7|bilirubin/)));
test('E11','Negative and positive stool observations are mutually exclusive',p=>{p.base('E');p.msel('readmitProblems','jaundice');p.msel('readmitJaundiceSigns','no pale stools');p.msel('readmitJaundiceSigns','pale stools');},r=>both(r,n=>{assert.match(n,/Pale stools/);assert.doesNotMatch(n,/No pale stools|Neither dark urine nor pale stools/);}));
test('E12','Uncomplicated prior course is not silently compatible with pre-discharge illness',p=>{p.base('E');p.seg('readmitPrior','uneventful');p.input('readmitDischargeDate','2026-09-23');p.msel('readmitProblems','apnea');p.input('rm_apnea_onset','2');},r=>assert.doesNotMatch(r.review.conflicts,/未發現衝突/));
test('E13','E prior intubation does not create a current procedure',p=>{p.base('E');p.msel('readmitProblems','respiratory');p.event('birth','intubation');},r=>assert.equal(r.procedureIntubation,'false'));
test('D01','Birth day equals DOL 1 in both notes',p=>p.base('A'),r=>{assert.match(r.notes.adm,/This 1-day-old /);assert.match(r.notes.acc,/^DOL 1, PMA 39\+0/);} );
test('D02','Backdated admission calculates from admission date',p=>{p.base('E');p.input('admissionDate','2026-09-25');p.msel('readmitProblems','jaundice');},r=>{assert.match(r.notes.adm,/This 6-day-old /);assert.match(r.notes.acc,/^DOL 6, PMA 39\+5/);} );
test('D03','Invalid chronology remains visible as a review issue',p=>{p.base('E');p.input('readmitDischargeDate','2026-10-05');p.input('readmitOnsetDOL','20');p.msel('readmitProblems','respiratory');},r=>{assert.match(r.review.conflicts,/出院日期晚於/);assert.match(r.review.conflicts,/症狀開始 DOL 晚於/);} );
test('P01','Confirmed amniocentesis result does not emphasize unperformed NIPT',p=>{p.base('A');p.seg('amnio','normal');p.seg('nipt','none');},r=>{assert.match(r.notes.adm,/aCGH/);assert.doesNotMatch(r.notes.adm,/NIPT|noninvasive prenatal testing/);} );
test('P02','Maternal abnormalities use American spelling and replace negative assertion',p=>{p.base('A');p.click('[data-ryn="aph"] [data-v="yes"]');},r=>both(r,n=>{assert.match(n,/antepartum hemorrhage/);assert.doesNotMatch(n,/haemorrhage/);}));
test('P03','Manual rubella nonimmune result survives navigation',p=>{p.base('A');p.click('.scr-row[data-scr="rubella"] input[value="nd"]');p.phase('birth:dr');p.phase('course:route');},r=>{assert.match(r.notes.adm,/rubella IgG was nonreactive/);assert.doesNotMatch(r.notes.adm,/rubella IgG was reactive/);} );
test('V01','Invalid transport parameter remains flagged after changing stage',p=>{p.base();p.phase('course:route');p.seg('obRespType','cpap');p.input('obFiO2','150');p.phase('course:obCare');p.click('[data-flow-target="finalReviewCard"]');},r=>assert.match(r.review.conflicts,/FiO|範圍/));
test('V02','Invalid evaluation SpO2 remains flagged after changing stage',p=>{p.base('E');p.msel('readmitProblems','respiratory');p.phase('course:evaluation');p.input('readmitSpO2','150');p.phase('course:illness');p.click('[data-flow-target="finalReviewCard"]');},r=>assert.match(r.review.conflicts,/SpO|範圍/));
test('V03','Unknown onset does not add temporal connective implying new disease',p=>{p.base('E');p.msel('readmitProblems','respiratory');p.msel('rm_respiratory_symptoms','cough');},r=>both(r,n=>{assert.match(n,/infant had cough/);assert.doesNotMatch(n,/developed cough/);}));
test('V04','Episode counts should reject fractions or prompt review',p=>{p.base('E');p.msel('readmitProblems','apnea');p.phase('course:illness');p.input('rm_apnea_count','1.5');},r=>assert.doesNotMatch(r.review.conflicts,/未發現衝突/));
test('V05','Malformed birth time should not become a documented time',p=>{p.base('A');p.input('birthTime','9999');},r=>both(r,n=>assert.doesNotMatch(n,/at 99:99/)));
test('F01','Prenatal clinic is not a confirmed birth or transfer hospital',p=>{p.base();p.input('obFacility','');p.input('ancPlace','Example Prenatal Clinic');},r=>both(r,n=>assert.doesNotMatch(n,/delivered[^.]*at Example Prenatal Clinic|transferred from Example Prenatal Clinic/)));
test('F02','Admission status supplied as a predicate needs a subject',p=>{p.base('A');p.input('obAdmissionStatus','had mild retractions');p.seg('resp','room air');},r=>both(r,n=>assert.doesNotMatch(n,/; had mild retractions|, had mild retractions/)));
test('F03','Unclassified intubation must not silently become our procedure',p=>{p.base();const id=p.event('outside','intubation');p.input('event-'+id+'-phase','');},r=>assert.equal(r.procedureIntubation,'false'));
test('G05','Multiple problems form a natural list rather than repeated and',p=>{p.base('E');for(const x of ['respiratory','fever','poor-feeding'])p.msel('readmitProblems',x);},r=>both(r,n=>assert.doesNotMatch(n,/respiratory symptoms and fever and poor feeding/)));
test('G06','Care-only acceptance closing reflects the already-entered care reason',p=>{p.base('E');p.seg('readmitSource','scheduled');p.msel('readmitProblems','care');p.input('rm_care_reason','temporary caregiver unavailability');},r=>assert.doesNotMatch(r.notes.acc,/with ____ for further evaluation and treatment/));
test('G07','Abnormal-screen acceptance does not discard an entered referral reason',p=>{p.base('E');p.msel('readmitProblems','abnormal-screen');p.input('rm_screen_test','newborn screening');p.input('rm_screen_result','an elevated screening marker');},r=>assert.doesNotMatch(r.notes.acc,/with ____ for further evaluation and treatment/));
console.log(JSON.stringify({total:results.length,pass:results.filter(r=>r.status==='pass').length,fail:results.filter(r=>r.status==='fail').length,harnessErrors:results.filter(r=>r.status==='harness-error').length,outdir}));
if(outdir)fs.writeFileSync(outdir+'/narratives.txt',results.map(r=>`${r.id} ${r.description}\n${r.status}\nADMISSION\n${r.notes?.adm||r.reason}\n\nACCEPTANCE\n${r.notes?.acc||''}\n`).join('\n\n'));
if(results.some(r=>r.status!=='pass'))process.exitCode=1;
module.exports={page};
